ncap project
neuromatch/NeuroAI_Course pull request #150
Opened 2024-05-06 20:24 UTC by glibesyck

2024-05-06 22:44 UTC, iamzoltan requested changes
Looks like there are artifacts from colab. Can you try to clean them up?

There also seems to be some issues with images. How are you embedding them?

2024-05-06 22:44 UTC, iamzoltan commented on projects/project-notebooks/NeuralCircuitArchitecturalPriors.ipynb
> +    "![image.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABPoAAAIjCAYAAACam3VxAAAABHNCSVQICAgIfAhkiAAAABl0RVh0U29mdHdhcmUAZ25vbWUtc2NyZWVuc2hvdO8Dvz4AAAAtdEVYdENyZWF0aW9uIFRpbWUAVHVlIDMwIEFwciA
why is this image like this?

2024-05-06 22:44 UTC, iamzoltan commented on projects/project-notebooks/NeuralCircuitArchitecturalPriors.ipynb
> +    "## 1.4 Example of simple modific
same here

2024-05-06 22:44 UTC, iamzoltan commented on projects/project-notebooks/NeuralCircuitArchitecturalPriors.ipynb
> +    "## 1.4 Example of simple modific
why is there widget state?

2024-05-06 22:44 UTC, iamzoltan commented on projects/project_materials.yml
> +#     title: Example Past Project
looks good

2024-05-07 13:17 UTC, glibesyck commented
added & updated in #148.

2024-05-07 13:17 UTC, closed without merging